version: '3.8'

services:
  # 后端服务
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: context-compression-backend
    ports:
      - "8000:8000"  # 后端API端口
    volumes:
      - ./data:/app/data  # 持久化用户数据目录
    environment:
      - PYTHONPATH=/app
      - DATA_DIR=/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app-network

  # 前端服务
  frontend:
    build:
      context: ./frontend/context-compression-frontend
      dockerfile: Dockerfile
    container_name: context-compression-frontend
    ports:
      - "80:80"   # 前端web端口
      - "443:443" # HTTPS端口 (如果需要)
    depends_on:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  app_data:
    driver: local